plugins {
    id 'com.android.application'
}

android {
    namespace 'com.il2calc.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.il2calc.app.v212'
        minSdk 23
        targetSdk 35
        versionCode 212
        versionName '2.1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
